### PR TITLE
Request

### PR DESCRIPTION
**Pull request by TinkerGnome**
two small suggestions:
- add simple error handling
- limit decimal precision to 3 digits

### CODE REVIEW

**Comment by fieldOfView** [comment]
~~~Could you elaborate a bit? What errors need handling? Why does the precision need limiting?~~~

Edit: Doh! I saw the title of this issue, and did not notice it is a PR (instead of a feature-request)

**Comment by fieldOfView** [comment]
Could you tell what sort of errors you were getting? I'm not a big fan of wrapping everything in a big try/catch, and would rather fix the individual issues.

**Comment by TinkerGnome** [comment]
Well, for example - if "gcode_list[0]" or "gcode_list[2]" does not exists (for whatever reason), it throws an "NoneType..."-exception and the output file is not written at all.
"gcode_dict" and "gcode_list" are also not checked before use (if it are valid objects), i don't know if Cura assures that you always get a valid list back from "getattr"?

The "global" try/catch is just my simple attempt to take sure that at least the unchanged file will be written, if the plugin fails (no matter what the reason is).

Oh - and regarding the decimal precision: if the first layer height has the default value of 0.27 and the z-offset is +0.03, the line changes to "G0 .... Z0.30000000004" (or something similar). It does not hurt, but it looks bad...

BTW: no need to merge the pull request, just take it as an idea an make it better!  😃

**Comment by fieldOfView** [comment]
I have added some error checking around the cases you mention. Beyond these, if the internal data structure is not what the plugin expects, something is very broken in Cura, and things _should_ break so Cura gets fixed (or the plugin gets updated to match what changed in Cura).

I have also fixed the rounding issue that could occur due to Python's inability to add up 0.1 and 0.2. Thanks for the contribution @TinkerGnome.

**Pull request closed without merging**
