### PR TITLE
Add support for a separate initial layer offset

### PR DESCRIPTION
**Pull request by FacuM**
# Description

This change adds support for a new setting called "Initial Layer Z Offset" which would bring the possibility for having both a common offset **and** a specific offset for the initial layer, allowing to keep a squished material on the bed throughout the first layer while making sure that the rest don't get squished and/or make the nozzle hit the print.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Behavior

The new setting "Initial Layer Z Offset" automatically matches the value of "Z Offset" unless manually modified by the user. If the value of either of these settings doesn't match with each other the new logic will trigger and generate proper G-code for both the initial layer and its subsequent layers.

### CODE REVIEW

**Comment by fieldOfView** [comment]
I am sorry, I don't understand the request.

The plugin offsets all layers together by design. If you only want to offset the first layer, then that would create an offset (lack of adhesion) between the first and the second layer.

Allow me to explain in ASCII art:

```
A:     B:     C:
---    ___    ---
---    ___    ---
---    ___    ---
---    ___    ___
```
A is the original gcode. B is all the layers offset by what this plugin does now. C would be your suggestion. See the gap between the first and the second layer?

**Comment by FacuM** [comment]
> I am sorry, I don't understand the request.
> 
> The plugin offsets all layers together by design. If you only want to offset the first layer, then that would create an offset (lack of adhesion) between the first and the second layer.
> 
> Allow me to explain in ASCII art:
> 
> ```
> A:     B:     C:
> ---    ___    ---
> ---    ___    ---
> ---    ___    ---
> ---    ___    ___
> ```
> 
> A is the original gcode. B is all the layers offset by what this plugin does now. C would be your suggestion. See the gap between the first and the second layer?

Yes, that's exactly what I'm trying to provide support for! This is what happens with my printer: if I want to, I can get it to squish the filament at the bottom of the build plate, which gives it an amazing texture. However, as the print progresses, it becomes more likely that the print head will knock the print.

This patch allows for the fine tuning of these two events: I **do** want a squished first layer, but I don't want to play too much with the tolerances of the mechanics within the Z-axis throughout the rest of the movements.

For testing, I've put out a few prints with "Initial Layer Z Offset" set to 0mm and "Z Offset" set to 0.05mm, I can attach a few pics if you want me to :).

**Comment by fieldOfView** [comment]
This will create an underextrusion between the first and the second layer. I don't see how that is a good thing.

Additionally your implementation only works the way you expect it to work if the "extensive processing" option is enabled.

**Comment by FacuM** [comment]
> This will create an underextrusion between the first and the second layer. I don't see how that is a good thing.
> 
> Additionally your implementation only works the way you expect it to work if the "extensive processing" option is enabled.

Damn, that was a terrible bug! I've now made sure that it'll only appear enabled upon ticking the "Extensive Z Offset Processing" box since I actually need to go through each line in order to stick to the variable offsetting. I could patch the other algorithm in order to match the same logic, but that would make it as slow as the extensive mode, so it wouldn't make much sense.

**Comment by fieldOfView** [comment]
>  I could patch the other algorithm in order to match the same logic,

No, you would just need to readjust the coordinate system at the start of the second layer.

I am still not convinced I agree with the functionality. You are of course free to use your forked version of the plugin like this, but I am not looking forward to explaining people who use this feature because they think that is what they want to do why there is an underextrusion between their first and second layer.

**Pull request closed without merging**
